### ISSUE TITLE
What's the meaning of COHORTS in the whole code?

### ISSUE THREAD

**Issue by Peterdingpeng** [talipucar/PyFlow_DomainAdaptation#2]
Dear Talip Ucar, 

      What's the meaning of COHORTS in the whole code?
      Kind regards, 

                     Peter

**Comment by talipucar** [comment]
It refers to clusters. I use the words "cluster" and "cohorts" (as in "patient cohorts" in healthcare)  interchangeably, but I should not have hard-coded it. I will update it and make the default wording as "cluster".

**Comment by talipucar** [comment]
Actually, my apologies, I answered without thinking. 

Cohorts refer to cohort of patients (in healthcare). Let us say that you have 3 different domains (or data modalities), for 5 groups of patients. In this case, you would have 5 cohorts in each of 3 domains. You can use this repo to align / adapt these patient groups across different modalities.

You can also consider cohorts as clusters. If you have 5 clusters in each of 3 domains, you can align corresponding clusters across all domains by learning their shared embedding.

Does this help?

**Comment by Peterdingpeng** [comment]
> Actually, my apologies, I answered without thinking.
> 
> Cohorts refer to cohort of patients (in healthcare). Let us say that you have 3 different domains (or data modalities), for 5 groups of patients. In this case, you would have 5 cohorts in each of 3 domains. You can use this repo to align / adapt these patient groups across different modalities.
> 
> You can also consider cohorts as clusters. If you have 5 clusters in each of 3 domains, you can align corresponding clusters across all domains by learning their shared embedding.
> 
> Does this help?

Thanks for your reply. I can understand the parameter of COHORT now.
Kind regards!

**Comment by talipucar** [comment]
Glad to hear that! Closing this issue...
